#debug: true

build:
  image: armdrone/drone-plugin-base
  commands:
    - apk update && apk add unzip curl
    - export VERSION=0.14
    - export URL=https://github.com/spf13/hugo/releases/download/v$(VERSION)/hugo_$(VERSION)_linux_arm.tar.gz
    - curl -L ${URL} > ./hugo.tar.gz
    - mkdir content/
    - tar xzf hugo.tar.gz -C content/
    - cd content && mv hugo*/hugo* ./hugo && cd -
    - ls -la content/

publish:
  docker:
#    environment:
#      - DOCKER_LAUNCH_DEBUG=true
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-hugo
    tag: 
      - latest
      - "0.14"

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: buildstatus
    username: Drone
    when:
      started: false
      success: true
      failure: true
